### ISSUE TITLE
modify chassis to use list instead of array 

### ISSUE THREAD

**Issue by Unionjackjz1** [EZ-Robotics/EZ-Template#13]
This is a step towards moving away from `setup.hpp` and declaring everything in the `initialize()` function in `main.cpp`.

**Comment by Unionjackjz1** [comment]
This created a new issue where l_motor and r_motor are no longer usable as telemetry for the user.  With #6, a constructor that is global should fix this.  

Adding @HakopZ to this issue.

**Comment by fishsticks89** [comment]
This should be fixed in the restructure; we'll see
