### ISSUE TITLE
Add limit switches to select autonomous mode

### ISSUE THREAD

**Issue by HakopZ** [EZ-Robotics/EZ-Template#34]
#### Is your feature request related to a problem? Please describe.
Adding a physical way to select auton 

#### Describe the solution you'd like
Using limit switches to switch between pages

#### Describe alternatives you've considered

Using a potentiometer 

#### Additional context

It's cool

**Comment by Unionjackjz1** [comment]
maybe this should allow 1 limit switch, where it will just increase the page?  so to go back a page you'd just spam the button until it wraps around.
