### ISSUE TITLE
Rotations sensors not working after upgrade to Pros 3.6.0 and.or VexOS 1.1.1

### ISSUE THREAD

**Issue by TRC27610** [EZ-Robotics/EZ-Template#58]
#### Expected Behavior
chassis.set_drive_pid(12, DRIVE_SPEED) should make the robot drive forwards 12 inches.

#### Actual Behavior
It drives backwards and seems to ignore subsequent drive commands.

#### Steps to Reproduce
Upgrade to Pros 3.6 and/or VexOS 1.1.1

#### Versions
Run `prosv5 conduct info-project` to see what versions you're running. 
PROS Kernel Version: 3.6.0
EZ-Template Version: 2.1.1

#### Additional Information
I was dumb and upgraded both the pros kernel to 3.6.0 and the vex brain to the latest firmware.  Afterwards, the rotation sensor seem to have stopped functioning properly.  Turns work.

#### Failure Logs
Screenshots or snippets of code that are causing issue.

**Comment by Unionjackjz1** [comment]
Rotation sensors haven't ever worked properly due to various reasons.  This should be fixed in 3.0.
