### ISSUE TITLE
Relative Set Angle 

### ISSUE THREAD

**Issue by HakopZ** [EZ-Robotics/EZ-Template#59]
Adding a relative set angle so that you can just say turn 45 instead of the absolute position.

**Comment by mkhlb** [comment]
as far as i can tell set angle sets the gyro AND the headingPID to the same thing, so the robot expressly won't turn when you set it, no?

**Comment by Unionjackjz1** [comment]
new func thats basically the exact same as set_turn_pid except its called something different (maybe set_relative_turn_pid() and the target is relative so
for example
youre facing absolute 270
set_turn_pid(90) would turn you relative 180 deg backwards to face absolute 90
set_relative_turn_pid(90) would turn you relative 90 forwards to face 360
so the target in relative is just gyroPID.target + parameter

New function for turning thats structurally identical to `set_turn_pid` except its called maybe `set_relative_turn_pid()`. 

For example:
Robot is facing absolute 270
 - `set_turn_pid(90)` would turn you relative 180 deg backwards to face absolute 90
 - `set_relative_turn_pid(90)` would turn you relative 90 forwards to face 360

The target in relative is just `gyroPID.target + parameter`.

**Comment by Unionjackjz1** [comment]
This should also apply for swing turns
