### ISSUE TITLE
Reevalute all function/variable names 

### ISSUE THREAD

**Issue by Unionjackjz1** [EZ-Robotics/EZ-Template#65]
Names weren't given much thought and should be as intuitive as possible.  This should be the final thing done along with #50 before the 3.0 beta is sent out. 

All auton selector relating things will be moved to [EZ-GUI](https://github.com/EZ-Robotics/EZ-GUI) and will be included with the example project by default.

**Comment by mkhlb** [comment]
function and method documentation comments should also on the docket for reevaluation

**Comment by Unionjackjz1** [comment]
`Remember 4" wheels are actually 4.125!` comments should be modified to remind new teams that only the old 4" wheels are 4.125, the new ones are 4". 

Maybe instead of modifying the comment in code, we have a place on the website to tell people what size their wheels are and how to figure out their drive ratio easier.

**Comment by Unionjackjz1** [comment]
The standardization of naming should lead to the (overdue) creation of contributing guidlines.

**Comment by Ryan4253** [comment]
use camalCase instead of snake_case?
