### ISSUE TITLE
Add Option To Reverse The Drive

### ISSUE THREAD

**Issue by Someone117** [EZ-Robotics/EZ-Template#79]
In the Over Under season, it is often necessary to push with one side of your bot and use a catapult for another. This creates the problem with driving backwards while trying to line up the bot to use the catapult.

In all the drive functions (arcade, tank etc.) a boolean parameter should be added that reverses the drive axis so that the robot can drive “backwards” when the operator wants. This could be as easy as a line in each of the drive functions:
`if (reverse) fwd_stick = -fwd_stick;`

**Comment by Unionjackjz1** [comment]
This will be added in v3 and has been done in #80
