### ISSUE TITLE
Derivative Kick

### ISSUE THREAD

**Issue by ssejrog** [EZ-Robotics/EZ-Template#99]
#### Expected Behavior
PID targets can be changed and the robot will switch to following the new target.

#### Actual Behavior
The robot follows a new target, but 1 iteration after the target has changed there is [derivative kick](https://apmonitor.com/pdc/index.php/Main/ProportionalIntegralDerivative#:~:text=Derivative%20kick%20occurs%20because%20the,an%20upper%20or%20lower%20bound.).  

This can be solved by getting the derivative of the input sensor value instead of error.

**Comment by Unionjackjz1** [comment]
Fixing this removes a (probably only used by me) strange behavior where you can set `target` and compute the PID with a `current` of `0`.  I do this in some of my code that's EZ-Template based, [here](https://github.com/EZ-Robotics/EZ-Tank-Odom/blob/7d584d2f258cf85f3e89b9f7acbb3d7d10a2dffb/src/EZ-Template/drive/pid_tasks.cpp#L165-L166) and [here](https://github.com/EZ-Robotics/EZ-Tank-Odom/blob/7d584d2f258cf85f3e89b9f7acbb3d7d10a2dffb/src/EZ-Template/drive/pid_tasks.cpp#L173-L175).

To keep this functionality, a new function was added to PID called `.compute_error()`.  You pass `error` and `current` into this, and it'll compute PID ignoring `target`.  `current` is only used for derivative calculation.
